<?php
//if( function_exists('acf_add_local_field_group') ):
//
//    acf_add_local_field_group(array(
//        'key' => 'group_5efdb7d7d47d7',
//        'title' => 'Agent',
//        'fields' => array(
//            array(
//                'key' => 'field_5f024c243e8ee',
//                'label' => 'Agent Description',
//                'name' => 'agent_description',
//                'type' => 'wysiwyg',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'tabs' => 'all',
//                'toolbar' => 'full',
//                'media_upload' => 1,
//                'delay' => 0,
//            ),
//            array(
//                'key' => 'field_5efdb7ecef912',
//                'label' => 'Service Areas',
//                'name' => 'agent_service_areas',
//                'type' => 'text',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'maxlength' => '',
//            ),
//            array(
//                'key' => 'field_5efdb831ef913',
//                'label' => 'Specialties',
//                'name' => 'agent_specialties',
//                'type' => 'text',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'maxlength' => '',
//            ),
//            array(
//                'key' => 'field_5efdb84aef914',
//                'label' => 'Email Address',
//                'name' => 'agent_email',
//                'type' => 'text',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '50',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'maxlength' => '',
//            ),
//            array(
//                'key' => 'field_5efdb863ef915',
//                'label' => 'Position',
//                'name' => 'agent_position',
//                'type' => 'text',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '50',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'maxlength' => '',
//            ),
//            array(
//                'key' => 'field_5efdb88f3e770',
//                'label' => 'Company Name',
//                'name' => 'agent_company_name',
//                'type' => 'text',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '50',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'maxlength' => '',
//            ),
//            array(
//                'key' => 'field_5efdb8983e771',
//                'label' => 'License',
//                'name' => 'agent_license',
//                'type' => 'text',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '50',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'maxlength' => '',
//            ),
//            array(
//                'key' => 'field_5efdb8a93e772',
//                'label' => 'Tax Number',
//                'name' => 'agent_tax_number',
//                'type' => 'text',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '50',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'maxlength' => '',
//            ),
//            array(
//                'key' => 'field_5efdb8b73e773',
//                'label' => 'Mobile Number',
//                'name' => 'agent_mobile',
//                'type' => 'text',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '50',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'maxlength' => '',
//            ),
//            array(
//                'key' => 'field_5efdb8c73e774',
//                'label' => 'Office Number',
//                'name' => 'agent_office_number',
//                'type' => 'text',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '50',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'maxlength' => '',
//            ),
//            array(
//                'key' => 'field_5efdb8d33e775',
//                'label' => 'Language',
//                'name' => 'agent_language',
//                'type' => 'text',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '50',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'maxlength' => '',
//            ),
//            array(
//                'key' => 'field_5efdb9646b75a',
//                'label' => 'Website',
//                'name' => 'agent_website',
//                'type' => 'text',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '50',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'maxlength' => '',
//            ),
//            array(
//                'key' => 'field_5efdbc5fbc64c',
//                'label' => 'Social profiles',
//                'name' => 'agent_social',
//                'type' => 'repeater',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'collapsed' => '',
//                'min' => 0,
//                'max' => 0,
//                'layout' => 'table',
//                'button_label' => '',
//                'sub_fields' => array(
//                    array(
//                        'key' => 'field_5efdbc98bc64d',
//                        'label' => 'Link',
//                        'name' => 'link',
//                        'type' => 'link',
//                        'instructions' => '',
//                        'required' => 0,
//                        'conditional_logic' => 0,
//                        'wrapper' => array(
//                            'width' => '',
//                            'class' => '',
//                            'id' => '',
//                        ),
//                        'return_format' => 'url',
//                    ),
//                    array(
//                        'key' => 'field_5efdbd0180150',
//                        'label' => 'Social icon',
//                        'name' => 'social_icon',
//                        'type' => 'image',
//                        'instructions' => '',
//                        'required' => 0,
//                        'conditional_logic' => 0,
//                        'wrapper' => array(
//                            'width' => '',
//                            'class' => '',
//                            'id' => '',
//                        ),
//                        'return_format' => 'array',
//                        'preview_size' => 'thumbnail',
//                        'library' => 'all',
//                        'min_width' => '',
//                        'min_height' => '',
//                        'min_size' => '',
//                        'max_width' => '',
//                        'max_height' => '',
//                        'max_size' => '',
//                        'mime_types' => '',
//                    ),
//                ),
//            ),
//            array(
//                'key' => 'field_5f158463a0db1',
//                'label' => 'Properties',
//                'name' => 'agent_properties',
//                'type' => 'relationship',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'acfe_permissions' => '',
//                'post_type' => array(
//                    0 => 'property',
//                ),
//                'taxonomy' => '',
//                'filters' => array(
//                    0 => 'search',
//                ),
//                'elements' => array(
//                    0 => 'featured_image',
//                ),
//                'min' => '',
//                'max' => '',
//                'return_format' => 'id',
//                'acfe_bidirectional' => array(
//                    'acfe_bidirectional_enabled' => '1',
//                    'acfe_bidirectional_related' => array(
//                        0 => 'field_5f024fed69682',
//                    ),
//                ),
//            ),
//        ),
//        'location' => array(
//            array(
//                array(
//                    'param' => 'post_type',
//                    'operator' => '==',
//                    'value' => 'agent',
//                ),
//            ),
//        ),
//        'menu_order' => 0,
//        'position' => 'normal',
//        'style' => 'default',
//        'label_placement' => 'top',
//        'instruction_placement' => 'label',
//        'hide_on_screen' => '',
//        'active' => true,
//        'description' => '',
//        'acfe_display_title' => '',
//        'acfe_autosync' => '',
//        'acfe_permissions' => '',
//        'acfe_form' => 0,
//        'acfe_meta' => '',
//        'acfe_note' => '',
//    ));
//
//    acf_add_local_field_group(array(
//        'key' => 'group_5efc7f9a053c7',
//        'title' => 'Options',
//        'fields' => array(
//            array(
//                'key' => 'field_5efc80319b723',
//                'label' => 'Search',
//                'name' => '',
//                'type' => 'tab',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'placement' => 'top',
//                'endpoint' => 0,
//            ),
//            array(
//                'key' => 'field_5efc806366043',
//                'label' => 'Search fields',
//                'name' => 'property_search_fields',
//                'type' => 'checkbox',
//                'instructions' => 'Search fields available in builder',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'choices' => array(
//                    'property_year_built' => 'Year Built',
//                    'property_bedrooms' => 'Bedrooms',
//                    'property_bath' => 'Bath',
//                    'property_garages' => 'Garages',
//                    'property_rooms' => 'Rooms',
//                    'property_living_area' => 'Living Area',
//                    'property_terrace' => 'Terrace',
//                ),
//                'allow_custom' => 0,
//                'default_value' => array(
//                ),
//                'layout' => 'vertical',
//                'toggle' => 0,
//                'return_format' => 'value',
//                'save_custom' => 0,
//            ),
//            array(
//                'key' => 'field_5efc7fefe0bcd',
//                'label' => 'Price',
//                'name' => '',
//                'type' => 'tab',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'placement' => 'top',
//                'endpoint' => 0,
//            ),
//            array(
//                'key' => 'field_5efca73391cde',
//                'label' => 'Currency',
//                'name' => 'property_currency',
//                'type' => 'select',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'choices' => array(
//                    'dollar' => '&#36; Dollar',
//                    'euro' => '&euro; Euro',
//                ),
//                'default_value' => array(
//                ),
//                'allow_null' => 0,
//                'multiple' => 0,
//                'ui' => 0,
//                'return_format' => 'value',
//                'ajax' => 0,
//                'placeholder' => '',
//            ),
//            array(
//                'key' => 'field_5efc86fbcb30a',
//                'label' => 'Thousands Separator',
//                'name' => 'property_price_separator',
//                'type' => 'radio',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'choices' => array(
//                    'comma' => 'Comma (e.g. 1,000,000)',
//                    'dot' => 'Period (e.g. 1.000.000)',
//                ),
//                'allow_null' => 0,
//                'other_choice' => 0,
//                'default_value' => '',
//                'layout' => 'vertical',
//                'return_format' => 'value',
//                'save_other_choice' => 0,
//            ),
//        ),
//        'location' => array(
//            array(
//                array(
//                    'param' => 'options_page',
//                    'operator' => '==',
//                    'value' => 'hello_builder',
//                ),
//            ),
//        ),
//        'menu_order' => 0,
//        'position' => 'normal',
//        'style' => 'default',
//        'label_placement' => 'top',
//        'instruction_placement' => 'label',
//        'hide_on_screen' => '',
//        'active' => true,
//        'description' => '',
//    ));
//
//    acf_add_local_field_group(array(
//        'key' => 'group_5ecbc332768f3',
//        'title' => 'Property',
//        'fields' => array(
//            array(
//                'key' => 'field_5ece73951c6a8',
//                'label' => 'Description',
//                'name' => '',
//                'type' => 'tab',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'placement' => 'left',
//                'endpoint' => 0,
//            ),
//            array(
//                'key' => 'field_5ece73ab1c6a9',
//                'label' => 'Description',
//                'name' => 'property_description',
//                'type' => 'wysiwyg',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'tabs' => 'all',
//                'toolbar' => 'full',
//                'media_upload' => 1,
//                'delay' => 0,
//            ),
//            array(
//                'key' => 'field_5eccf7325d16c',
//                'label' => 'Price info',
//                'name' => '',
//                'type' => 'tab',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'placement' => 'left',
//                'endpoint' => 0,
//            ),
//            array(
//                'key' => 'field_5eccf8b911327',
//                'label' => 'Price',
//                'name' => 'property_price',
//                'type' => 'number',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '30',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'min' => '',
//                'max' => '',
//                'step' => '',
//            ),
//            array(
//                'key' => 'field_5efcbadc002ae',
//                'label' => 'Period',
//                'name' => 'property_offer_period',
//                'type' => 'select',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '30',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'choices' => array(
//                    'none' => 'None',
//                    'per_year' => 'per Year',
//                    'per_month' => 'per Month',
//                    'per_week' => 'per Week',
//                    'per_day' => 'per Day',
//                ),
//                'default_value' => array(
//                ),
//                'allow_null' => 0,
//                'multiple' => 0,
//                'ui' => 0,
//                'return_format' => 'value',
//                'ajax' => 0,
//                'placeholder' => '',
//            ),
//            array(
//                'key' => 'field_5eccf659c74f9',
//                'label' => 'Location',
//                'name' => '',
//                'type' => 'tab',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'placement' => 'left',
//                'endpoint' => 0,
//            ),
//            array(
//                'key' => 'field_5ecbcca33f249',
//                'label' => 'Map',
//                'name' => 'property_location',
//                'type' => 'google_map',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'center_lat' => '',
//                'center_lng' => '',
//                'zoom' => '',
//                'height' => '',
//            ),
//            array(
//                'key' => 'field_5ecd28c99a139',
//                'label' => 'Details',
//                'name' => '',
//                'type' => 'tab',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'placement' => 'left',
//                'endpoint' => 0,
//            ),
//            array(
//                'key' => 'field_5ecd2561689fa',
//                'label' => 'Property ID',
//                'name' => 'property_id',
//                'type' => 'text',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '50',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'maxlength' => '',
//            ),
//            array(
//                'key' => 'field_5ece88f18f174',
//                'label' => 'Year Built',
//                'name' => 'property_year_built',
//                'type' => 'date_picker',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '50',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'display_format' => 'F j, Y',
//                'return_format' => 'F j, Y',
//                'first_day' => 1,
//            ),
//            array(
//                'key' => 'field_5ece853bcb377',
//                'label' => 'Bedrooms',
//                'name' => 'property_bedrooms',
//                'type' => 'number',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '50',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'min' => '',
//                'max' => '',
//                'step' => '',
//            ),
//            array(
//                'key' => 'field_5ece880f3cb27',
//                'label' => 'Bath',
//                'name' => 'property_bath',
//                'type' => 'number',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '50',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'min' => '',
//                'max' => '',
//                'step' => '',
//            ),
//            array(
//                'key' => 'field_5ece899bb0d22',
//                'label' => 'Garages',
//                'name' => 'property_garages',
//                'type' => 'number',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '50',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'min' => '',
//                'max' => '',
//                'step' => '',
//            ),
//            array(
//                'key' => 'field_5ece89d3c56f3',
//                'label' => 'Rooms',
//                'name' => 'property_rooms',
//                'type' => 'number',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '50',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'min' => '',
//                'max' => '',
//                'step' => '',
//            ),
//            array(
//                'key' => 'field_5ece8b4dffe1c',
//                'label' => 'Living Area',
//                'name' => 'property_living_area',
//                'type' => 'number',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '50',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'min' => '',
//                'max' => '',
//                'step' => '',
//            ),
//            array(
//                'key' => 'field_5ece8b9ba3298',
//                'label' => 'Terrace',
//                'name' => 'property_terrace',
//                'type' => 'number',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '50',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '',
//                'placeholder' => '',
//                'prepend' => '',
//                'append' => '',
//                'min' => '',
//                'max' => '',
//                'step' => '',
//            ),
//            array(
//                'key' => 'field_5ecd9351a9072',
//                'label' => 'Media',
//                'name' => '',
//                'type' => 'tab',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'placement' => 'left',
//                'endpoint' => 0,
//            ),
//            array(
//                'key' => 'field_5ecd9361a9073',
//                'label' => 'Gallery',
//                'name' => 'property_gallery',
//                'type' => 'gallery',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'return_format' => 'array',
//                'preview_size' => 'medium',
//                'insert' => 'append',
//                'library' => 'all',
//                'min' => '',
//                'max' => '',
//                'min_width' => '',
//                'min_height' => '',
//                'min_size' => '',
//                'max_width' => '',
//                'max_height' => '',
//                'max_size' => '',
//                'mime_types' => '',
//            ),
//            array(
//                'key' => 'field_5f024fdf69681',
//                'label' => 'Agent',
//                'name' => '',
//                'type' => 'tab',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'placement' => 'top',
//                'endpoint' => 0,
//            ),
//            array(
//                'key' => 'field_5f024fed69682',
//                'label' => 'Property Agent',
//                'name' => 'property_agent',
//                'type' => 'relationship',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'acfe_permissions' => '',
//                'post_type' => array(
//                    0 => 'agent',
//                ),
//                'taxonomy' => '',
//                'filters' => array(
//                    0 => 'search',
//                ),
//                'elements' => array(
//                    0 => 'featured_image',
//                ),
//                'min' => '',
//                'max' => 1,
//                'return_format' => 'object',
//                'acfe_bidirectional' => array(
//                    'acfe_bidirectional_enabled' => true,
//                    'acfe_bidirectional_related' => array(
//                        0 => 'field_5f024fed69682',
//                        1 => 'field_5f158463a0db1',
//                    ),
//                ),
//            ),
//        ),
//        'location' => array(
//            array(
//                array(
//                    'param' => 'post_type',
//                    'operator' => '==',
//                    'value' => 'property',
//                ),
//            ),
//        ),
//        'menu_order' => 0,
//        'position' => 'normal',
//        'style' => 'default',
//        'label_placement' => 'top',
//        'instruction_placement' => 'label',
//        'hide_on_screen' => '',
//        'active' => true,
//        'description' => '',
//        'acfe_display_title' => '',
//        'acfe_autosync' => '',
//        'acfe_permissions' => '',
//        'acfe_form' => 0,
//        'acfe_meta' => '',
//        'acfe_note' => '',
//    ));
//
//    acf_add_local_field_group(array(
//        'key' => 'group_5f11cc6d60bd4',
//        'title' => 'Taxonomy meta',
//        'fields' => array(
//            array(
//                'key' => 'field_5f11cd9068771',
//                'label' => 'Color',
//                'name' => 'status_color',
//                'type' => 'color_picker',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'default_value' => '#06B236',
//            ),
//        ),
//        'location' => array(
//            array(
//                array(
//                    'param' => 'taxonomy',
//                    'operator' => '==',
//                    'value' => 'status',
//                ),
//            ),
//        ),
//        'menu_order' => 0,
//        'position' => 'normal',
//        'style' => 'default',
//        'label_placement' => 'top',
//        'instruction_placement' => 'label',
//        'hide_on_screen' => '',
//        'active' => true,
//        'description' => '',
//    ));
//
//endif;